version: 2.1

defaults: &defaults
  docker:
    - image: circleci/node:10.16.0
  working_directory: ~/project

jobs:
  test:
    <<: *defaults
    steps:
      - build
      - run:
          name: Run tests
          command: npm run test

  publish:
    <<: *defaults
    steps:
      - build
      - run:
          name: Authorize publish
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run:
          name: Publish
          command: npm publish

workflows:
  version: 2
  test-publish:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
      - publish:
          requires:
            - test
          filters:
            tags:
              only: /^v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
commands:
  build:
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Lint
          command: npm run lint
      - run:
          name: Build
          command: npm run build
